language: go

go:
  - 1.2
  - 1.3

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/dgrijalva/jwt-go

notifications:
  email:
    - cf-autoscale-eng@pivotallabs.com
